/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dcoms_assignment;


import java.rmi.Naming;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author Shatha
 */
public class HRForm extends javax.swing.JFrame {
    private RMIInterfaceMain hrService;
    private List<String[]> pendingLeaves;
    private int selectedLeaveId = -1;
    private int selectedEmpId   = -1;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HRForm.class.getName());

    /**
     * Creates new form HRForm
     */
    public HRForm() {
        initComponents();
        // Make table cells non-editable
        employeeTable.setDefaultEditor(Object.class, null);
        connectToServer();
        pendingList.addItemListener(e -> {
            if (e.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                onListClicked();
            }
        });
        loadPendingLeaves();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list4 = new java.awt.List();
        sidebarPanel = new javax.swing.JPanel();
        hrLabel = new javax.swing.JLabel();
        sideApplyReviewBtn = new javax.swing.JButton();
        sideRegisterBtn = new javax.swing.JButton();
        mainTabbedPane = new javax.swing.JTabbedPane();
        registerPanel = new javax.swing.JPanel();
        personalLabel = new javax.swing.JLabel();
        accountLabel = new javax.swing.JLabel();
        familyLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        firstNameField = new javax.swing.JTextField();
        icOrPassportField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        roleField = new javax.swing.JTextField();
        spouseNameField = new javax.swing.JTextField();
        numChildrenField = new javax.swing.JTextField();
        emergencyContactField = new javax.swing.JTextField();
        emergencyContactRelField = new javax.swing.JTextField();
        dependentDOBField = new javax.swing.JTextField();
        relationshipStatusFamilyField = new javax.swing.JTextField();
        dependentNameField = new javax.swing.JTextField();
        dependantRelationshipField = new javax.swing.JTextField();
        dateOfBirthField = new javax.swing.JTextField();
        genderField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        phoneNoField = new javax.swing.JTextField();
        relationshipStatusPersonalField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();
        applyReviewPanel = new javax.swing.JPanel();
        pendingList = new java.awt.List();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        rejectButton = new javax.swing.JButton();
        acceptButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crest Solutions - HR Management System");
        setPreferredSize(new java.awt.Dimension(1100, 660));
        setSize(new java.awt.Dimension(1100, 660));

        sidebarPanel.setBackground(new java.awt.Color(0, 150, 150));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(185, 0));
        sidebarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hrLabel.setFont(new java.awt.Font("Arial", 1, 54)); // NOI18N
        hrLabel.setForeground(new java.awt.Color(255, 255, 255));
        hrLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hrLabel.setText("HR");
        hrLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sidebarPanel.add(hrLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, -1, -1));

        sideApplyReviewBtn.setBackground(new java.awt.Color(0, 102, 102));
        sideApplyReviewBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sideApplyReviewBtn.setForeground(new java.awt.Color(255, 255, 255));
        sideApplyReviewBtn.setText("Apply Review");
        sideApplyReviewBtn.setToolTipText("");
        sideApplyReviewBtn.setBorderPainted(false);
        sideApplyReviewBtn.setFocusPainted(false);
        sideApplyReviewBtn.addActionListener(this::sideApplyReviewBtnActionPerformed);
        sidebarPanel.add(sideApplyReviewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 178, 155, 38));

        sideRegisterBtn.setBackground(new java.awt.Color(0, 102, 102));
        sideRegisterBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sideRegisterBtn.setForeground(new java.awt.Color(255, 255, 255));
        sideRegisterBtn.setText("Register Employee");
        sideRegisterBtn.setBorderPainted(false);
        sideRegisterBtn.setFocusPainted(false);
        sideRegisterBtn.addActionListener(this::sideRegisterBtnActionPerformed);
        sidebarPanel.add(sideRegisterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 130, 155, 38));

        registerPanel.setBackground(new java.awt.Color(15, 70, 70));
        registerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        personalLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        personalLabel.setForeground(new java.awt.Color(0, 200, 200));
        personalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personalLabel.setText("Personal details");
        registerPanel.add(personalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 160, 20));

        accountLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        accountLabel.setForeground(new java.awt.Color(0, 200, 200));
        accountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountLabel.setText("Account details");
        registerPanel.add(accountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 20));

        familyLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        familyLabel.setForeground(new java.awt.Color(0, 200, 200));
        familyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        familyLabel.setText("Family contact details");
        registerPanel.add(familyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 160, 20));

        lastNameField.setText("Last name");
        registerPanel.add(lastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 120, -1));

        firstNameField.setText("First name");
        registerPanel.add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 120, -1));

        icOrPassportField.setText("IC or Passport No.");
        registerPanel.add(icOrPassportField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 120, -1));

        usernameField.setText("Username");
        registerPanel.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 120, -1));

        roleField.setText("Role (e.g. HR)");
        registerPanel.add(roleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 120, -1));

        spouseNameField.setText("Spouse Name");
        registerPanel.add(spouseNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 120, -1));

        numChildrenField.setText("No. of children");
        numChildrenField.addActionListener(this::numChildrenFieldActionPerformed);
        registerPanel.add(numChildrenField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 120, -1));

        emergencyContactField.setText("Emergency contact");
        registerPanel.add(emergencyContactField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 120, -1));

        emergencyContactRelField.setText("EC relationship");
        registerPanel.add(emergencyContactRelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 120, -1));

        dependentDOBField.setText("Dependent DOB (YYYY-MM-DD)");
        registerPanel.add(dependentDOBField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 190, -1));

        relationshipStatusFamilyField.setText("Relationship status");
        registerPanel.add(relationshipStatusFamilyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 120, -1));

        dependentNameField.setText("Dependant name");
        registerPanel.add(dependentNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 120, -1));

        dependantRelationshipField.setText("Dependant relationship");
        registerPanel.add(dependantRelationshipField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 190, -1));

        dateOfBirthField.setText("Date of birth (YYYY-MM-DD)");
        registerPanel.add(dateOfBirthField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 170, -1));

        genderField.setText("Gender");
        registerPanel.add(genderField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 120, -1));

        addressField.setText("Address");
        registerPanel.add(addressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 120, -1));

        emailField.setText("Email");
        registerPanel.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 120, -1));

        phoneNoField.setText("Phone no.");
        phoneNoField.addActionListener(this::phoneNoFieldActionPerformed);
        registerPanel.add(phoneNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 120, -1));

        relationshipStatusPersonalField.setText("Relationship status");
        registerPanel.add(relationshipStatusPersonalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 120, -1));

        passwordField.addActionListener(this::passwordFieldActionPerformed);
        registerPanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 120, -1));

        registerButton.setBackground(new java.awt.Color(0, 180, 180));
        registerButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Register");
        registerButton.setBorderPainted(false);
        registerButton.setFocusPainted(false);
        registerButton.addActionListener(this::registerButtonActionPerformed);
        registerPanel.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 140, 40));

        mainTabbedPane.addTab("Register Employee", registerPanel);

        applyReviewPanel.setBackground(new java.awt.Color(15, 70, 70));
        applyReviewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pendingList.addActionListener(this::pendingListActionPerformed);
        applyReviewPanel.add(pendingList, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 550, 170));

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Employee ID", "Name", "Username", "Leave balance left"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(employeeTable);

        applyReviewPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 550, 100));

        rejectButton.setBackground(new java.awt.Color(180, 40, 40));
        rejectButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        rejectButton.setForeground(new java.awt.Color(255, 255, 255));
        rejectButton.setText("Reject");
        rejectButton.setBorderPainted(false);
        rejectButton.setFocusPainted(false);
        rejectButton.addActionListener(this::rejectButtonActionPerformed);
        applyReviewPanel.add(rejectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 100, 40));

        acceptButton.setBackground(new java.awt.Color(0, 160, 80));
        acceptButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        acceptButton.setForeground(new java.awt.Color(255, 255, 255));
        acceptButton.setText("Accept");
        acceptButton.setBorderPainted(false);
        acceptButton.setFocusPainted(false);
        acceptButton.addActionListener(this::acceptButtonActionPerformed);
        applyReviewPanel.add(acceptButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 100, 40));

        mainTabbedPane.addTab("Apply Review", applyReviewPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebarPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sideApplyReviewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideApplyReviewBtnActionPerformed
        // TODO add your handling code here:
            mainTabbedPane.setSelectedIndex(1);
            loadPendingLeaves();
    }//GEN-LAST:event_sideApplyReviewBtnActionPerformed

    private void sideRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideRegisterBtnActionPerformed
        // TODO add your handling code here:
        mainTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_sideRegisterBtnActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        onRegisterClicked();
    }//GEN-LAST:event_registerButtonActionPerformed

    private void phoneNoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNoFieldActionPerformed

    private void numChildrenFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numChildrenFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numChildrenFieldActionPerformed

    private void rejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectButtonActionPerformed
        // TODO add your handling code here:
        onRejectClicked();
    }//GEN-LAST:event_rejectButtonActionPerformed

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        // TODO add your handling code here:
        onAcceptClicked();
    }//GEN-LAST:event_acceptButtonActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void pendingListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendingListActionPerformed
        onListClicked();
    }//GEN-LAST:event_pendingListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HRForm().setVisible(true));
    }
private void connectToServer() {
        try {
            String url = "rmi://localhost:1044/HRMSService"; // matches ServerMain.rebind("HRMSService",...)
            hrService = (RMIInterfaceMain) Naming.lookup(url);
            System.out.println("[HR] Connected.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Cannot connect!\nStart ServerMain first.\n\n" + e.getMessage(),
                "Connection Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void onRegisterClicked() {
        if (hrService == null) { JOptionPane.showMessageDialog(this, "Not connected!"); return; }
        String firstName = getVal(firstNameField, "First name");
        String lastName  = getVal(lastNameField,  "Last name");
        String icOrPass  = getVal(icOrPassportField, "IC or Passport No.");
        String username  = getVal(usernameField,  "Username");
        String password  = new String(passwordField.getPassword()).trim();
        String role      = getVal(roleField, "Role (e.g. HR)");
        if (firstName.isEmpty() || lastName.isEmpty() || icOrPass.isEmpty()
                || username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Fill in: First Name, Last Name, IC/Passport, Username, Password.",
                "Missing Fields", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int numChildren = 0;
        try { numChildren = Integer.parseInt(getVal(numChildrenField, "No. of children")); }
        catch (NumberFormatException ex) { numChildren = 0; }
        try {
            int newId = hrService.registerEmployee(
                firstName, lastName, icOrPass, username, password,
                role.isEmpty() ? "EMPLOYEE" : role,
                getVal(spouseNameField,              "Spouse Name"),
                numChildren,
                getVal(dependentNameField,           "Dependant name"),
                getVal(dependantRelationshipField,   "Dependant relationship"),
                getVal(dependentDOBField,            "Dependent DOB (YYYY-MM-DD)"),
                getVal(relationshipStatusFamilyField,"Relationship status"),
                getVal(emergencyContactField,        "Emergency contact"),
                getVal(emergencyContactRelField,     "EC relationship"),
                getVal(dateOfBirthField,             "Date of birth (YYYY-MM-DD)"),
                getVal(genderField,                  "Gender"),
                getVal(addressField,                 "Address"),
                getVal(emailField,                   "Email"),
                getVal(phoneNoField,                 "Phone no.")
            );
            if (newId == -1) {
                JOptionPane.showMessageDialog(this, "FAILED. Username or IC already exists.",
                    "Failed", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                    "Registered! ID: " + newId + "  Name: " + firstName + " " + lastName,
                    "Success", JOptionPane.INFORMATION_MESSAGE);
                clearForm();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Server error:\n" + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadPendingLeaves() {
        if (hrService == null) return;
        try {
            pendingLeaves = hrService.getPendingLeaveRequests();
            pendingList.removeAll();
            javax.swing.table.DefaultTableModel tm =
                (javax.swing.table.DefaultTableModel) employeeTable.getModel();
            tm.setRowCount(0);
            selectedLeaveId = -1;
            selectedEmpId   = -1;
            if (pendingLeaves == null || pendingLeaves.isEmpty()) {
                pendingList.add("  (No pending leave requests)");
            } else {
                for (String[] r : pendingLeaves) {
                    pendingList.add(String.format(
                        "[ID:%s]  %-20s  %s  |  %s to %s  (%s days)  - %s",
                        r[0], r[2], r[3], r[4], r[5], r[6], r[7]));
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error:\n" + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void onListClicked() {
        int idx = pendingList.getSelectedIndex();
        if (idx < 0 || pendingLeaves == null || idx >= pendingLeaves.size()) return;
        String[] row = pendingLeaves.get(idx);
        selectedLeaveId = Integer.parseInt(row[0]);
        selectedEmpId   = Integer.parseInt(row[1]);
        try {
            String[] info = hrService.getEmployeeInfoById(selectedEmpId);
            javax.swing.table.DefaultTableModel tm =
                (javax.swing.table.DefaultTableModel) employeeTable.getModel();
            tm.setRowCount(0);
            if (info != null) tm.addRow(new Object[]{ info[0], info[1], info[2], info[3] });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error:\n" + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void onAcceptClicked() {
        if (selectedLeaveId == -1) {
            JOptionPane.showMessageDialog(this, "Select a request first.",
                "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (JOptionPane.showConfirmDialog(this,
                "Approve leave [ID: " + selectedLeaveId + "] ?",
                "Confirm", JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) return;
        try {
            boolean ok = hrService.reviewLeaveRequest(selectedLeaveId, "APPROVED", 1);
            JOptionPane.showMessageDialog(this,
                ok ? "Leave APPROVED." : "Failed — insufficient balance.",
                ok ? "Approved" : "Failed",
                ok ? JOptionPane.INFORMATION_MESSAGE : JOptionPane.ERROR_MESSAGE);
            if (ok) loadPendingLeaves();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error:\n" + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void onRejectClicked() {
        if (selectedLeaveId == -1) {
            JOptionPane.showMessageDialog(this, "Select a request first.",
                "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (JOptionPane.showConfirmDialog(this,
                "Reject leave [ID: " + selectedLeaveId + "] ?",
                "Confirm", JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) return;
        try {
            boolean ok = hrService.reviewLeaveRequest(selectedLeaveId, "REJECTED", 1);
            JOptionPane.showMessageDialog(this,
                ok ? "Leave REJECTED." : "Rejection failed.",
                ok ? "Rejected" : "Failed",
                ok ? JOptionPane.INFORMATION_MESSAGE : JOptionPane.ERROR_MESSAGE);
            if (ok) loadPendingLeaves();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error:\n" + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private String getVal(javax.swing.JTextField f, String placeholder) {
        String t = f.getText().trim();
        return t.equals(placeholder) ? "" : t;
    }

    private void clearForm() {
        firstNameField.setText("First name");
        lastNameField.setText("Last name");
        icOrPassportField.setText("IC or Passport No.");
        usernameField.setText("Username");
        passwordField.setText("");
        roleField.setText("Role (e.g. HR)");
        spouseNameField.setText("Spouse Name");
        numChildrenField.setText("No. of children");
        emergencyContactField.setText("Emergency contact");
        emergencyContactRelField.setText("EC relationship");
        dependentNameField.setText("Dependant name");
        dependantRelationshipField.setText("Dependant relationship");
        dependentDOBField.setText("Dependent DOB (YYYY-MM-DD)");
        relationshipStatusFamilyField.setText("Relationship status");
        dateOfBirthField.setText("Date of birth (YYYY-MM-DD)");
        genderField.setText("Gender");
        addressField.setText("Address");
        emailField.setText("Email");
        phoneNoField.setText("Phone no.");
        relationshipStatusPersonalField.setText("Relationship status");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JLabel accountLabel;
    private javax.swing.JTextField addressField;
    private javax.swing.JPanel applyReviewPanel;
    private javax.swing.JTextField dateOfBirthField;
    private javax.swing.JTextField dependantRelationshipField;
    private javax.swing.JTextField dependentDOBField;
    private javax.swing.JTextField dependentNameField;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField emergencyContactField;
    private javax.swing.JTextField emergencyContactRelField;
    private javax.swing.JTable employeeTable;
    private javax.swing.JLabel familyLabel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JTextField genderField;
    private javax.swing.JLabel hrLabel;
    private javax.swing.JTextField icOrPassportField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameField;
    private java.awt.List list4;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JTextField numChildrenField;
    private javax.swing.JPasswordField passwordField;
    private java.awt.List pendingList;
    private javax.swing.JLabel personalLabel;
    private javax.swing.JTextField phoneNoField;
    private javax.swing.JButton registerButton;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JButton rejectButton;
    private javax.swing.JTextField relationshipStatusFamilyField;
    private javax.swing.JTextField relationshipStatusPersonalField;
    private javax.swing.JTextField roleField;
    private javax.swing.JButton sideApplyReviewBtn;
    private javax.swing.JButton sideRegisterBtn;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JTextField spouseNameField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
